### PR TITLE
In-place pack mod updating

### PR DESCRIPTION
**Pull request by Caedis**
This is mainly for me, but it could be useful to other devs who update to nightly often.
Currently, this is mods only. Configs are not touched.

`generate_nightly` will need to be ran before hand

```
poetry run python -m gtnh.cli.generate_nightly --update-available
poetry run python -m gtnh.cli.update_pack_inplace [--use-symlink] <Side> "<.minecraft path>"
```

Side can be one of: CLIENT, SERVER, CLIENT_JAVA9, SERVER_JAVA9  
The `--use-symlink` flag can be supplied if you want mods to be symlinked from the cache (only on posix systems)

An example to update the mods on my server:
`poetry run python -m gtnh.cli.update_pack_inplace SERVER_JAVA9 "/mnt/rootshare/appdata/minecraft/gtnh/"`

and on my local computer:  
`poetry run python -m gtnh.cli.update_pack_inplace CLIENT_JAVA9 "/mnt/games/Minecraft/Instances/GTNH Nightly/.minecraft/"`

Quotes are only needed if the path contains spaces which can be escaped instead if you want.

To have certain mods excluded from the local pack, create a `.inplace_mod_exclusions` file in the root of the project and include the mod names from gtnh-assets.json  

Example (I use RTG + CC, ModernControlling, and Xaero's)
```
Realistic-World-Gen
DefaultWorldGenerator
Controlling
JourneyMap
JourneyMap Server
```

### CODE REVIEW

**Comment by Caedis** [comment]
Note, it will not catch custom versions of jars in the pack (like a `-pre` tag you built and tagged locally)

**Comment by Caedis** [comment]
First thing I have really done in python, so please give any criticism.

**Review by mitchej123 — APPROVED** [review]
seems reasonable enough

**Comment by Caedis** [comment]
Gonna hold off until the other PR is merged so I can make logging changes here as well

**Pull request merged**
