### PR TITLE
Add icon to MMC pack export

### PR DESCRIPTION
**Pull request by wlhlm**
Make GTNH look as pretty as it can be in MMC.

### CODE REVIEW

**Comment by boubou19** [comment]
will review this in a couple of hours

**Comment by wlhlm** [comment]
I've only tested this in Prism, but I don't think that functionality has changed since the original fork.

**Comment by Dream-Master** [comment]
mmc and prsim works
prism add the version very quick mmc need about 3 mins for import

**Comment by Dream-Master** [comment]
image
image

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
