### PR TITLE
update to reflect examplemod changes

### PR DESCRIPTION
**Pull request by bombcar**

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]

**Comment by leagris** [comment]
Too bad the update does not include .editorconfig

**Comment by bombcar** [comment]
> Too bad the update does not include .editorconfig

https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/214f9f1e998ff2ac8c270cb93db1d6620425727d/update_buildscript.sh#L8 ? but it does ...

**Comment by leagris** [comment]
It is for all GTNH projects, so no, it is to be included into each repository. Other than that, I know how to download this file from the ExampleMod and I already documented this into our Wiki.

**Comment by bombcar** [comment]
> It is for all GTNH projects, so no, it is to be included into each repository. Other than that, I know how to download this file from the ExampleMod and I already documented this into our Wiki.

I linked the updatescript that copies it into the repository? I’m confused as to what more you expect it to do ….

**Pull request merged**
